version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: eensterkwachtwoord
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
     networks:
      - app-network

   wp:
     build:
      context: ./web
      dockerfile: Dockerfile
     depends_on:
       - db
     restart: always
     ports:
       - "8000:80"
     volumes:
       - ./htdocs:/var/www/html
       - ./:/var/www/html/wp-content/plugins/my-plugin
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: wordpress
       WORDPRESS_TABLE_PREFIX: wp_
       WORDPRESS_DEBUG: '1'
     networks:
       - app-network

   wpcli:
    image: wordpress:cli
    user: 33:33
    depends_on:
      - db
      - wp
    volumes:
      - ./.data:/var/www/html
      - ./wpcli/usr/local/bin/wp-setup.sh:/usr/local/bin/wp-setup
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    networks:
      - app-network
   
   caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/etc/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/etc/caddy/certs:/etc/caddy/certs:ro
    networks:
      - app-network

volumes:
    db_data: {}
    php_data: {}

networks:
  app-network:
    driver: bridge