version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: eensterkwachtwoord
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wp:
     build:
      context: ./wp
      dockerfile: Dockerfile
     depends_on:
       - db
     restart: always
     volumes:
       - ./.htdocs:/var/www/html
       - ./:/var/www/html/wp-content/plugins/my-plugin
       - ./wp/usr/local/etc/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: wordpress
       WORDPRESS_TABLE_PREFIX: wp_
       WORDPRESS_DEBUG: '1'
     extra_hosts:
       - "host.docker.internal:host-gateway"

   wpcli:
    image: wordpress:cli
    user: 33:33
    depends_on:
      - db
      - wp
    volumes:
      - ./.htdocs:/var/www/html
      - ./wpcli/usr/local/bin/wp-setup.sh:/usr/local/bin/wp-setup
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
   
   caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/etc/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/etc/caddy/certs:/etc/caddy/certs:ro

volumes:
    db_data: {}
    php_data: {}

